### ISSUE TITLE
AWS Lambda nodejs-apig issue with invoking function with a test event 

### ISSUE THREAD

**Issue by glarence** [glarence/verishop-onboarding#2]
Source: https://github.com/awsdocs/aws-lambda-developer-guide/tree/main/sample-apps/nodejs-apig

"An error occurred (InvalidRequestContentException) when calling the Invoke operation: Could not parse request body into json: Could not parse payload into json: Unexpected character ('­' (code 173)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"��(�������m���D�y�^�Ɯq�m��m���i�'�*'�m�_��V��X�jب��f��=�f�{�n��j�j����<j�e�ƭ����('yױr���"; line: 1, column: 2]"

**Comment by zhangxian97** [comment]
what is your request? Can you paste your full request here?

**Comment by glarence** [comment]
this is the 3-invoke.ssh

#!/bin/bash
set -eo pipefail
FUNCTION=$(aws cloudformation describe-stack-resource --stack-name nodejs-apig --logical-resource-id function --query 'StackResourceDetail.PhysicalResourceId' --output text)

while true; do
  aws lambda invoke --function-name $FUNCTION --payload file://event.json out.json
  cat out.json
  echo ""
  sleep 2
done
